name: Pipeline Sistema Bancario

on:
  push:
    branches: [ "principal", "main" ]
  pull_request:
    branches: [ "principal", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar el codigo
      uses: actions/checkout@v4
      with:
        ref: principal # Fuerza a GitHub a descargar tu codigo real

    - name: Configurar MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Configurar NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Configurar VSTest (Para las Pruebas)
      uses: microsoft/setup-vstest@v1.0.5

    - name: Restaurar paquetes NuGet
      run: nuget restore SistemaBancario_P1.sln

    - name: Compilar Solucion Completa
      run: msbuild SistemaBancario_P1.sln /p:Configuration=Debug

    - name: Ejecutar Pruebas Unitarias Automaticas
      run: vstest.console.exe SistemaBancario.Tests\bin\Debug\SistemaBancario.Tests.dll
